version: '3'
services:
  web:
    container_name: server
    image: nginx
    ports: 
      - "80:80"
      - "443:443"
    volumes:
      - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
      - python
    networks:
      - chatbot
  app:
    container_name: app
    image: php:fpm-alpine3.19
    ports:
      - "9000:9000"
    volumes:
      - ./app:/var/www/html
    command: ["php-fpm", "-F"]
    networks:
      - chatbot
  python:
    container_name: python
    image: python
    volumes:
      - ./python:/app
    networks:
      - chatbot

networks:
  chatbot:
    driver: bridge